insert into country (name) values ('United States');

insert into prog_language (name) values ('Cobol');
insert into prog_language (name) values ('Nim');
insert into prog_language (name) values ('Crystal');
insert into prog_language (name) values ('Elixir');
insert into prog_language (name) values ('F#');
insert into prog_language (name) values ('Haskell');
insert into prog_language (name) values ('OCaml');
insert into prog_language (name) values ('Erlang');
insert into prog_language (name) values ('Clojure');
insert into prog_language (name) values ('Racket');
insert into prog_language (name) values ('Elm');
insert into prog_language (name) values ('Lua');
insert into prog_language (name) values ('Zig');
insert into prog_language (name) values ('Pony');
insert into prog_language (name) values ('Idris');
insert into prog_language (name) values ('PureScript');
insert into prog_language (name) values ('Pharo');
insert into prog_language (name) values ('Forth');
insert into prog_language (name) values ('J');
insert into prog_language (name) values ('Prolog');
insert into prog_language (name) values ('Mercury');
insert into prog_language (name) values ('Reason');
insert into prog_language (name) values ('Mojo');
insert into prog_language (name) values ('Oberon');
insert into prog_language (name) values ('Coq');
insert into prog_language (name) values ('D');
insert into prog_language (name) values ('Hack');
insert into prog_language (name) values ('R');
insert into prog_language (name) values ('Q');
insert into prog_language (name) values ('Alice');
insert into prog_language (name) values ('Eiffel');
insert into prog_language (name) values ('Ceylon');
insert into prog_language (name) values ('Bend');

insert into industry (name) values ('AI/ML');
insert into industry (name) values ('Blockchain/Web3');
insert into industry (name) values ('Finance');
insert into industry (name) values ('Food and Beverage');
insert into industry (name) values ('Games');
insert into industry (name) values ('Insurance');
insert into industry (name) values ('IT');
insert into industry (name) values ('Legal');
insert into industry (name) values ('Other');

insert into salary (base) values (200000);
insert into salary (base) values (300000);
insert into salary (base) values (400000);
insert into salary (base) values (500000);